package com.rokid.glass.mediastream.capture

enum class MediaErrorCode {
    PERMISSION_REQUIRED,
    SDK_NOT_READY,
    SDK_DISCONNECTED,
    CAMERA_IN_USE,
    CAMERA_START_TIMEOUT,
    VIDEO_FRAME_TIMEOUT,
    AUDIO_START_FAILED,
    AUDIO_DATA_TIMEOUT,
    SERVER_UNREACHABLE,
    RECEIVER_NOT_READY,
    WEBRTC_NEGOTIATION_FAILED,
    NETWORK_DISCONNECTED,
}
